-- Indexes for the exact filters on `request_logs`, which `015_log_keyset.sql`
-- deliberately left out pending a measurement. This is that measurement, taken
-- on a 75,610-row install.
--
-- Every unindexed exact filter cost a full table scan whenever it matched
-- nothing or matched rarely, which is the common case while a name is being
-- typed and the whole case when an operator asks about traffic that turns out
-- not to exist. `bun:sqlite` is synchronous, so that scan is the event loop:
-- 15ms in which no proxied request moves, growing linearly with retention.
--
--   filter                   before    after
--   resolved_model (miss)    15.7ms    0.1ms
--   error_code (miss)        15.0ms    0.0ms
--   resolved_provider miss   14.2ms    0.0ms
--   model, either column     17.2ms    0.0ms   (697ms on a cold cache)
--
-- The `model` filter is why this stopped being optional. It is the one clause
-- that is an OR — `requested_model = ? OR resolved_model = ?` — and an OR over
-- two unindexed columns cannot stop early at all: the page limit bounds what is
-- returned, not what is compared. With both indexes present the planner reaches
-- it as a MULTI-INDEX OR, unioning two seeks.
--
-- **That plan is a real trade, not a free win, and neither side is bounded by
-- the page.** The union arrives in two orders, neither of them `at DESC`, so it
-- is sorted in a temp B-tree — which means the limit stops being an early exit
-- for this plan too: which 101 rows are newest is unknown until everything
-- matching has been collected. So the ordered scan pays for how *rare* a value
-- is and the union pays for how *common* it is, and both grow with the table:
--
--   rows        ordered scan, miss   MULTI-INDEX OR, 55% of rows match
--   75,000      10.6ms                3.1ms
--   300,000     44.7ms               12.5ms
--   1,000,000  148.9ms               41.0ms
--
-- Chosen anyway, for two reasons. The union's worst case is some 3.6x smaller at
-- the same size. And it is the worst case an operator *asked for* — a full page
-- of the model that is most of their traffic — where the scan's worst case is
-- the one they produce by accident: a typo, a half-typed name, or asking whether
-- a model appears at all. A time bound rescues the scan as well (149ms to 1.8ms
-- over the newest 1%), but nothing requires one, and the union needs no help.
--
-- If a large log with one dominant model makes the common case hurt, the levers
-- are a time bound or `resolved:`/`requested:`, which plan as one seek with no
-- union to sort. Past that, the upgrade is a covering index on
-- `(at DESC, id DESC)` including both model columns, letting the ordered scan
-- test them without fetching rows.
--
-- Trap: **`ANALYZE` reverses this.** With `sqlite_stat1` present the planner
-- costs the union's sort against the ordered scan and picks the scan — 17ms
-- again, silently, on exactly the case these indexes exist for. Measured: the
-- plan is a MULTI-INDEX OR at 5,000 rows and an ordered scan at the same 5,000
-- rows once `ANALYZE` has run.
--
-- `migrations.test.ts` asserts the plan, but on an empty database, so it cannot
-- see that reversal: the damage is to a plan, on data the suite does not have.
-- What guards it is a second test asserting nothing under `src/` runs `ANALYZE`
-- at all. Whoever needs to run it re-measures the `model` filter first.
--
-- `state` gets nothing: `idx_request_logs_pending` already covers the only
-- selective half, and `state = 'done'` is every row, so the keyset index fills
-- a page immediately. Still nothing per-column for `failed`, whose predicate is
-- `state = 'done' AND status >= 400` and which reads at 1.0ms off the keyset
-- index, because failures cluster near the head an operator is looking at.
--
-- Each index leads with the filtered column and continues with the keyset pair,
-- so one seek answers the filter and the walk from it is already in page order.
-- Measured cost of the four: 2.6us to 4.7us per inserted row, which is noise
-- beside a request that spends seconds upstream.
CREATE INDEX idx_request_logs_resolved_model ON request_logs (resolved_model, at DESC, id DESC);
CREATE INDEX idx_request_logs_requested_model ON request_logs (requested_model, at DESC, id DESC);
CREATE INDEX idx_request_logs_error_code ON request_logs (error_code, at DESC, id DESC);
CREATE INDEX idx_request_logs_provider ON request_logs (resolved_provider, at DESC, id DESC);
